"""Source adapters. ArtSource is the plug-in contract (spec §6.2) so
Smithsonian/Cleveland/Rijksmuseum can be added later without pipeline changes.

A plain MODULE can satisfy this Protocol (mypy supports modules as protocol
implementations) — met.py is consumed as `from .sources import met`."""
from pathlib import Path
from typing import Protocol


class ArtSource(Protocol):
    def search(self, query: str, *, has_images: bool = True, limit: int = 50) -> list[int]: ...
    def fetch_meta(self, object_id: int) -> dict: ...
    def fetch_image(self, meta: dict, dest: Path) -> Path: ...
    def validate_cc0(self, meta: dict) -> tuple[bool, str]: ...
    def parse_candidate(self, meta: dict) -> dict: ...
